name: Linting

on:
  push:
    branches:
      - master
      - next
      - beta
  pull_request:
    branches:
      - master
      - next
      - beta

jobs:
  check-commit:
    name: Check Commit Messages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v6

  lint-dockefie:
    name: Linting Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7 
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ./dockeriles
          recursive: true